spring.profiles.active=dev
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

identity.query.provider=sunat

sunat.identity.base-url=https://e-consultaruc.sunat.gob.pe
sunat.identity.connect-timeout=20s
sunat.identity.request-timeout=40s
sunat.identity.user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36

eldni.identity.query-url=https://eldni.com/pe/buscar-datos-por-dni
eldni.identity.connect-timeout=20s
eldni.identity.request-timeout=30s
eldni.identity.user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36
