spring.profiles.active=dev

app.file.storage-root=${APP_FILE_STORAGE_ROOT:./data/uploads}
app.file.public-base-url=${APP_FILE_PUBLIC_BASE_URL:}
app.file.maximum-size-bytes=${APP_FILE_MAXIMUM_SIZE_BYTES:10485760}
server.forward-headers-strategy=framework
