-- Plantilla inactiva: el asistente confirma el ambiente antes de habilitar los envios.
-- Rerunnable: conserva credenciales, RUC y seleccion activa ya configurados.
-- URLs oficiales: https://cpe.sunat.gob.pe/guias-y-manuales
INSERT INTO `sunat_config` (
    `SunatConfigCod`,
    `IssuerRuc`,
    `SolUser`,
    `SolPassword`,
    `CertificatePath`,
    `CertificatePassword`,
    `CertificateType`,
    `Environment`,
    `StorageBasePath`,
    `InvoiceEndpoint`,
    `SummaryEndpoint`,
    `TicketEndpoint`,
    `GuideEndpoint`,
    `GuideTokenEndpoint`,
    `GuideClientId`,
    `GuideClientSecret`,
    `MaxSendAttempts`,
    `MaxTicketAttempts`,
    `SchedulerEnabled`,
    `AutomaticRetryEnabled`,
    `ActiveConfig`,
    `CreationUser`,
    `CreationDate`,
    `ModifyUser`,
    `ModifyDate`,
    `Status`
) VALUES (
    'SUNAT_TEST_BETA',
    '20123456789',
    'MODDATOS',
    'MODDATOS',
    'classpath:certificate/certificado_prueba.pfx',
    'taqini',
    'PFX',
    'BETA',
    'storage/sunat',
    'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService',
    'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService',
    'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService',
    'https://api-cpe.sunat.gob.pe/v1/contribuyente/gem',
    'https://api-seguridad.sunat.gob.pe/v1/clientessol/{client_id}/oauth2/token/',
    NULL,
    NULL,
    3,
    3,
    'N',
    'N',
    'N',
    'SISTEMA',
    NOW(),
    NULL,
    NOW(),
    'A'
)
ON DUPLICATE KEY UPDATE
    `InvoiceEndpoint` = VALUES(`InvoiceEndpoint`),
    `SummaryEndpoint` = VALUES(`SummaryEndpoint`),
    `TicketEndpoint` = VALUES(`TicketEndpoint`),
    `GuideEndpoint` = VALUES(`GuideEndpoint`),
    `GuideTokenEndpoint` = VALUES(`GuideTokenEndpoint`),
    `CertificatePath` = VALUES(`CertificatePath`),
    `StorageBasePath` = VALUES(`StorageBasePath`);
