INSERT INTO `sunat_config` (
    `SunatConfigCod`,
    `IssuerRuc`,
    `SolUser`,
    `SolPassword`,
    `CertificatePath`,
    `CertificatePassword`,
    `CertificateType`,
    `Environment`,
    `StorageBasePath`,
    `InvoiceEndpoint`,
    `SummaryEndpoint`,
    `TicketEndpoint`,
    `MaxSendAttempts`,
    `MaxTicketAttempts`,
    `SchedulerEnabled`,
    `AutomaticRetryEnabled`,
    `ActiveConfig`,
    `CreationUser`,
    `CreationDate`,
    `ModifyUser`,
    `ModifyDate`,
    `Status`
) VALUES (
    'SUNAT_TEST_BETA',
    '20123456789',
    'MODDATOS',
    'MODDATOS',
    'C:/proyectos/multiple/total_ccadmin/backend/ws_wa_sunat_ccadmin/src/main/resources/certificate/certificado_prueba.pfx',
    'taqini',
    'PFX',
    'BETA',
    'C:/proyectos/multiple/total_ccadmin/backend/ws_wa_sunat_ccadmin/storage/sunat',
    'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService',
    'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService',
    'https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService',
    3,
    3,
    'N',
    'N',
    'S',
    'SISTEMA',
    NOW(),
    NULL,
    NOW(),
    'A'
)
ON DUPLICATE KEY UPDATE
    `IssuerRuc` = VALUES(`IssuerRuc`),
    `SolUser` = VALUES(`SolUser`),
    `SolPassword` = VALUES(`SolPassword`),
    `CertificatePath` = VALUES(`CertificatePath`),
    `CertificatePassword` = VALUES(`CertificatePassword`),
    `CertificateType` = VALUES(`CertificateType`),
    `Environment` = VALUES(`Environment`),
    `StorageBasePath` = VALUES(`StorageBasePath`),
    `InvoiceEndpoint` = VALUES(`InvoiceEndpoint`),
    `SummaryEndpoint` = VALUES(`SummaryEndpoint`),
    `TicketEndpoint` = VALUES(`TicketEndpoint`),
    `MaxSendAttempts` = VALUES(`MaxSendAttempts`),
    `MaxTicketAttempts` = VALUES(`MaxTicketAttempts`),
    `SchedulerEnabled` = VALUES(`SchedulerEnabled`),
    `AutomaticRetryEnabled` = VALUES(`AutomaticRetryEnabled`),
    `ActiveConfig` = VALUES(`ActiveConfig`),
    `ModifyUser` = 'SISTEMA',
    `ModifyDate` = NOW(),
    `Status` = 'A';
