package com.local.app.pinpad.enums;

public enum PinpadErrorCode {
    INVALID_REQUEST,
    UNAUTHORIZED_AGENT,
    PINPAD_BUSY,
    PAYMENT_NOT_FOUND,
    IDEMPOTENCY_AMOUNT_MISMATCH,
    INVALID_PAYMENT_STATUS,
    PINPAD_TIMEOUT,
    PINPAD_REJECTED,
    PINPAD_CANCELLED,
    PINPAD_ERROR,
    STORAGE_ERROR,
    UNKNOWN_ERROR
}
